# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
    # Highlight active window borders: https://github.com/FelixKratz/JankyBorders
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0',
    'exec-and-forget /Users/will/dotfiles/aerospace/scripts/aerospace-save_restore.sh restore'
]

# Start AeroSpace at login
start-at-login = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
# on-focused-monitor-changed = 'move-mouse monitor-lazy-center'

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

# Assign workspaces to specific monitors
[workspace-to-monitor-force-assignment]
    # Primary
    a = "LG HDR 4K"
    s = "LG HDR 4K"
    d = "LG HDR 4K"
    f = "LG HDR 4K"
    g = "LG HDR 4K"
    h = "LG HDR 4K"
    j = "LG HDR 4K"
    k = "LG HDR 4K"
    l = "LG HDR 4K"

    # Dedicated
    n = "Built-in Retina Display"
    m = "CB272K"

[mode.main.binding]
    # Workspace
    # ------------------------------------------------------------------------
    shift-alt-a = 'workspace a'
    shift-alt-s = 'workspace s'
    shift-alt-d = 'workspace d'
    shift-alt-f = 'workspace f'
    shift-alt-g = 'workspace g'
    shift-alt-h = 'workspace h'
    shift-alt-j = 'workspace j'
    shift-alt-k = 'workspace k'
    shift-alt-l = 'workspace l'

    shift-alt-n = 'workspace n'
    shift-alt-m = 'workspace m'

    # Focus
    # ------------------------------------------------------------------------
    # See: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-k         = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-l         = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-o         = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

    cmd-alt-o         = 'move-node-to-monitor --wrap-around --focus-follows-window up'
    cmd-alt-k         = 'move-node-to-monitor --wrap-around --focus-follows-window left'
    cmd-alt-l         = 'move-node-to-monitor --wrap-around --focus-follows-window down'
    cmd-alt-semicolon = 'move-node-to-monitor --wrap-around --focus-follows-window right'
    # cmd-alt-o         = 'focus-monitor up'
    # cmd-alt-k         = 'focus-monitor left'
    # cmd-alt-l         = 'focus-monitor down'
    # cmd-alt-semicolon = 'focus-monitor right'

    cmd-alt-j = 'focus-monitor LG HDR 4K'
    cmd-alt-n = 'focus-monitor Built-in Retina Display'
    cmd-alt-m = 'focus-monitor CB272K'
    # ------------------------------------------------------------------------

    # Move
    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    # ------------------------------------------------------------------------
    ctrl-alt-a = 'move-node-to-workspace a'
    ctrl-alt-s = 'move-node-to-workspace s'
    ctrl-alt-d = 'move-node-to-workspace d'
    ctrl-alt-f = 'move-node-to-workspace f'
    ctrl-alt-g = 'move-node-to-workspace g'
    ctrl-alt-h = 'move-node-to-workspace h'
    ctrl-alt-j = 'move-node-to-workspace j'
    ctrl-alt-k = 'move-node-to-workspace k'
    ctrl-alt-l = 'move-node-to-workspace l'

    ctrl-alt-n = 'move-node-to-workspace n'
    ctrl-alt-m = 'move-node-to-workspace m'

    ctrl-cmd-k         = 'move left'
    ctrl-cmd-l         = 'move down'
    ctrl-cmd-o         = 'move up'
    ctrl-cmd-semicolon = 'move right'

    shift-cmd-k         = 'join-with left'
    shift-cmd-l         = 'join-with down'
    shift-cmd-o         = 'join-with up'
    shift-cmd-semicolon = 'join-with right'
    # ------------------------------------------------------------------------

    # Toggle fullscreen
    ctrl-cmd-f = "fullscreen"

    # See: https://nikitabobko.github.io/AeroSpace/commands#layout
    ctrl-cmd-i = 'layout tiles horizontal vertical'
    ctrl-cmd-p = 'layout accordion horizontal vertical'

    # See: https://nikitabobko.github.io/AeroSpace/commands#resize
    # shift-alt-minus = 'resize smart -50'
    # shift-alt-equal = 'resize smart +50'

    # See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'focus-back-and-forth'
    # # See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    # alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-cmd-s = 'mode service'


# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    b = ['balance-sizes', 'mode main'] # Balance sizes of windows in the current workspace
    e = 'enable toggle' # Toggle Aerospace on/off
    down = 'volume down'
    up = 'volume up'
    shift-down = ['volume set 0', 'mode main']
    # backspace = ['close-all-windows-but-current', 'mode main']
    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    # s = ['layout sticky tiling', 'mode main']
